# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-03 14:36
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0431\u0440\u0435\u043d\u0434\u0430')),
            ],
            options={
                'db_table': 'brand_product',
                'verbose_name_plural': '\u0411\u0440\u0435\u043d\u0434\u044b',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(help_text='Slug for product url created from name.', unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-delimited set of SEO keywords for meta tag', max_length=255, verbose_name='Meta keywords')),
                ('meta_title', models.CharField(blank=True, max_length=80, verbose_name='Meta title')),
                ('meta_description', models.CharField(blank=True, help_text='Content for description meta tags', max_length=200, verbose_name='Meta description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='Parent-category for current category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.Category', verbose_name='Parent category')),
            ],
            options={
                'ordering': ['-created_at'],
                'db_table': 'categories',
                'verbose_name_plural': 'Categories',
            },
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043a\u0443\u043f\u043e\u043d\u0430')),
                ('identifier', models.CharField(max_length=256, verbose_name='\u0418\u0434\u0435\u043d\u0442\u0438\u0444\u0438\u043a\u0430\u0442\u043e\u0440')),
                ('percent', models.CharField(max_length=10, verbose_name='\u041f\u0440\u043e\u0446\u0435\u043d\u0442 \u0441\u043a\u0438\u0434\u043a\u0438')),
            ],
            options={
                'verbose_name_plural': '\u0421\u0438\u0441\u0442\u0435\u043c\u0430 \u043a\u0443\u043f\u043e\u043d\u043e\u0432',
            },
        ),
        migrations.CreateModel(
            name='FeelName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u0412\u043a\u0443\u0441')),
            ],
            options={
                'db_table': 'Feel_product',
                'verbose_name_plural': '\u0412\u043a\u0443\u0441',
            },
        ),
        migrations.CreateModel(
            name='GiftPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u043f\u043e\u0434\u0430\u0440\u043a\u0430')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='\u0426\u0435\u043d\u0430')),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=b'gifts/images/', verbose_name='\u0424\u043e\u0442\u043e \u043f\u043e\u0434\u0430\u0440\u043a\u0430')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='\u0412\u0435\u0441')),
            ],
            options={
                'ordering': ['-price'],
                'db_table': 'gift_price',
                'verbose_name_plural': '\u041f\u043e\u0434\u0430\u0440\u043a\u0438',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(help_text='Unique value for product page URL, created from name.', max_length=255, unique=True, verbose_name='Slug')),
                ('not_available', models.BooleanField(verbose_name='\u041d\u0435\u0442 \u0432 \u043d\u0430\u043b\u0438\u0447\u0438\u0438')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='\u041b\u0443\u0447\u0448\u0438\u0435 \u043f\u0440\u043e\u0434\u0430\u0436\u0438')),
                ('is_aqua', models.BooleanField(verbose_name='\u0416\u0438\u0434\u043a\u043e\u0441\u0442\u044c')),
                ('is_new', models.BooleanField(verbose_name='\u041d\u043e\u0432\u0438\u043d\u043a\u0430')),
                ('description', ckeditor.fields.RichTextField()),
                ('old_id', models.CharField(blank=True, max_length=20, verbose_name='id \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b \u0441\u043e \u0441\u0442\u0430\u0440\u043e\u0433\u043e \u0441\u0430\u0439\u0442\u0430 \u0434\u043b\u044f \u0440\u0435\u0434\u0438\u0440\u0435\u043a\u0442\u0430')),
                ('meta_title', models.CharField(blank=True, help_text='\u0422\u0435\u0433 title', max_length=255, verbose_name='Meta title')),
                ('meta_description', models.CharField(blank=True, help_text='Content for description meta tag', max_length=255, verbose_name='Meta description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('brand_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.BrandName', verbose_name='\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0431\u0440\u0435\u043d\u0434\u0430')),
                ('categories', models.ManyToManyField(help_text='Categories for product', to='catalog.Category', verbose_name='Categories')),
                ('feel', models.ManyToManyField(blank=True, null=True, to='catalog.FeelName', verbose_name='\u0412\u043a\u0443\u0441')),
                ('itemsAttached', models.ManyToManyField(blank=True, related_name='_product_itemsAttached_+', to='catalog.Product', verbose_name='\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u043f\u0440\u0438\u043b\u0430\u0433\u0430\u044e\u0449\u0438\u0435\u0441\u044f \u0442\u043e\u0432\u0430\u0440\u044b')),
            ],
            options={
                'ordering': ['-created_at'],
                'db_table': 'products',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(help_text=b'Product image', upload_to=b'products/images/')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('default', models.BooleanField(default=False, verbose_name='\u041e\u0441\u043d\u043e\u0432\u043d\u043e\u0435 \u0444\u043e\u0442\u043e')),
                ('product', models.ForeignKey(help_text='Referenced product', on_delete=django.db.models.deletion.CASCADE, to='catalog.Product', verbose_name='Product')),
            ],
            options={
                'db_table': 'product_images',
                'verbose_name_plural': '\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='ProductVolume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='\u041e\u0431\u044a\u0435\u043c')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='\u0412\u0435\u0441')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='\u0426\u0435\u043d\u0430')),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=9, verbose_name='\u041d\u043e\u0432\u0430\u044f \u0446\u0435\u043d\u0430')),
                ('default', models.BooleanField(default=False, verbose_name='\u041e\u0441\u043d\u043e\u0432\u043d\u043e\u0439 \u043d\u0430\u0431\u043e\u0440')),
                ('product', models.ForeignKey(help_text='Referenced product', on_delete=django.db.models.deletion.CASCADE, to='catalog.Product', verbose_name='Product')),
            ],
            options={
                'db_table': 'product_volume',
                'verbose_name_plural': '\u041e\u0441\u043d\u043e\u0432\u043d\u044b\u0435 \u0430\u0442\u0440\u0438\u0431\u0443\u0442\u044b',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u0412\u0430\u0448\u0435 \u0438\u043c\u044f')),
                ('review', models.TextField(verbose_name='\u0422\u0435\u043a\u0441\u0442')),
                ('photo', models.FileField(upload_to=b'reviews/images/', verbose_name='\u0424\u043e\u0442\u043e')),
            ],
            options={
                'verbose_name_plural': '\u041e\u0442\u0437\u044b\u0432\u044b',
            },
        ),
    ]
