# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-05 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='feel',
            field=models.ManyToManyField(blank=True, to='catalog.FeelName', verbose_name='\u0412\u043a\u0443\u0441'),
        ),
    ]
