# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-03 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(help_text=b'Product image', upload_to=b'products/images/'),
        ),
    ]
