# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-13 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20160505_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(default=1, help_text='\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u043f\u0440\u043e\u0434\u0443\u043a\u0442 \u043a \u043a\u043e\u0442\u043e\u0440\u043e\u043c\u0443 \u043e\u0442\u043d\u043e\u0441\u0438\u0442\u044c\u0441\u044f \u0434\u0430\u043d\u043d\u044b\u0439 \u043e\u0442\u0437\u044b\u0432', on_delete=django.db.models.deletion.CASCADE, to='catalog.Product', verbose_name='\u041f\u0440\u043e\u0434\u0443\u043a\u0442'),
            preserve_default=False,
        ),
    ]
