# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-04 12:31
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewsProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor.fields.RichTextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(help_text='\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u043f\u0440\u043e\u0434\u0443\u043a\u0442 \u043a \u043a\u043e\u0442\u043e\u0440\u043e\u043c\u0443 \u043e\u0442\u043d\u043e\u0441\u0438\u0442\u044c\u0441\u044f \u0434\u0430\u043d\u043d\u044b\u0439 \u043e\u0442\u0437\u044b\u0432', on_delete=django.db.models.deletion.CASCADE, to='catalog.Product', verbose_name='\u041f\u0440\u043e\u0434\u0443\u043a\u0442')),
                ('userProfile', models.ForeignKey(help_text='\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f \u043a \u043a\u043e\u0442\u043e\u0440\u043e\u043c\u0443 \u043e\u0442\u043d\u043e\u0441\u0438\u0442\u0441\u044f \u0434\u0430\u043d\u043d\u044b\u0439 \u043e\u0442\u0437\u044b\u0432', on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile', verbose_name='\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c')),
            ],
        ),
    ]
